- name: cloud-native-development-apb playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    openshift_user: 
    openshift_password: 
    openshift_token:

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules

  tasks:    
  - name: login as super user with token
    shell: "oc login --token={{ openshift_token }} --insecure-skip-tls-verify=true"
    ignore_errors: true
    when:
      - openshift_token is defined
      - openshift_token is not none
      - openshift_token|trim() != ""

  - name: login as super user with pwd
    shell: "oc login -u {{ openshift_user }} -p {{ openshift_password }} --insecure-skip-tls-verify=true"
    ignore_errors: true
    when: >
      openshift_token is not defined or
      openshift_token is none or
      openshift_token|trim() == ""
          
  - name: Delete infrastructyre services from {{ namespace }}
    command: "oc delete all,cm,secret,pvc,sa -l app={{ item }} -n {{ namespace }}"
    ignore_errors: true
    with_items:
      - gogs
      - nexus
      - guides-codeready
      - postgres
      - keycloak
      - che
      - che-operator
  
  - name: Delete CodeReady Workspaces additional resources from {{ namespace }}
    command: "oc delete {{ item }} codeready-workspaces-operator -n {{ namespace }}"
    ignore_errors: true
    with_items:
      - serviceaccount
      - rolebinding

  - name: Delete Local Kiali if existing
    block:
      - name: check if {{ infra_project_name }} project exists
        command: "oc delete project {{ infra_project_name }}"
        register: project_result
        ignore_errors: true
    vars:
      infra_project_name: "infra-mcouliba"
    # vars:
    #   infra_project_name: "infra-{{ item }}"
    # with_sequence: start=1 end=100 format="user%d"
